included:
    - Sources
    - Tests
disabled_rules:
  - force_try
  - identifier_name
  - line_length
  - function_body_length
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - todo
