# Travis CI build file for Kitura-NIO.
# Runs on Linux (Ubuntu v14.04).

# whitelist (branches that should be built)
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      env: SWIFT_SNAPSHOT=4.1
    - os: linux
      dist: trusty
      sudo: true
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=4.1

script:
  - ./build.sh
