# Travis CI build file for Kitura-NIO.
# Runs on Linux (Ubuntu v14.04).

# whitelist (branches that should be built)
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      env: SWIFT_SNAPSHOT=4.1

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
